name: Update Dependencies

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Update dependencies
        run: |
          bun update
          
      - name: Run tests
        run: |
          bun run lint
          bun run type-check
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "deps: update dependencies"
          title: "chore: update dependencies"
          body: |
            ## Dependencies Update
            
            This PR updates all dependencies to their latest versions.
            
            - All linting checks passed ✅
            - Type checking passed ✅
            - Build successful ✅
            
            🤖 Auto-generated by GitHub Actions
          branch: deps/update-dependencies
          delete-branch: true